const globals = Object.fromEntries([
  "AudioContext", "Buffer", "Element", "Event", "HTMLElement", "Notification",
  "__dirname", "clearInterval", "clearTimeout", "console", "document", "exports",
  "globalThis", "isFinite", "module", "process", "require", "setInterval",
  "setTimeout", "structuredClone", "window"
].map(name => [name, "readonly"]));

module.exports = [{
  files: ["src/**/*.js", "scripts/**/*.{cjs,mjs}", "test/**/*.cjs", "*.mjs"],
  ignores: ["main.js", "node_modules/**"],
  languageOptions: { ecmaVersion:"latest", sourceType:"module", globals },
  rules: {
    "constructor-super": "error",
    "eqeqeq": ["error", "always", { null:"ignore" }],
    "for-direction": "error",
    "getter-return": "error",
    "no-async-promise-executor": "error",
    "no-constant-binary-expression": "error",
    "no-constant-condition": ["error", { checkLoops:false }],
    "no-dupe-args": "error",
    "no-dupe-class-members": "error",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty": ["error", { allowEmptyCatch:false }],
    "no-fallthrough": "error",
    "no-func-assign": "error",
    "no-import-assign": "error",
    "no-loss-of-precision": "error",
    "no-new-native-nonconstructor": "error",
    "no-obj-calls": "error",
    "no-promise-executor-return": "error",
    "no-self-assign": "error",
    "no-setter-return": "error",
    "no-sparse-arrays": "error",
    "no-unexpected-multiline": "error",
    "no-unreachable": "error",
    "no-unreachable-loop": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unused-private-class-members": "error",
    "no-unused-vars": ["error", { args:"after-used", caughtErrors:"none" }],
    "no-useless-assignment": "error",
    "no-useless-backreference": "error",
    "no-useless-catch": "error",
    "no-useless-escape": "error",
    "no-with": "error",
    "require-yield": "error",
    "use-isnan": "error",
    "valid-typeof": "error"
  }
}];
